### ISSUE TITLE
Issue with the imdbpy dependency? 

### ISSUE THREAD

**Issue by julesfowler** [oscarpredictor/oscar-predictor#35]
Hello! I'm taking the tutorial in a coupla days, and I'm having some trouble getting `imdbpy` installed correctly -- figured I would open an issue. 

When I do the pip install with a requirements file (or trying literally pip install the version 5.0) I get an error in the imdbpy setup file -- looks like some of that setup file is still `Python 2.0`. 

I tried pulling a newer version, and any of the 6 versions seemingly install without issue, but don't recognize the import unless I go work directly in the `site-packages`. 

Were you expecting us to use a `Python 2` environment? Has anyone else had trouble with this install? Does it need to be the `5.0` version? 

(Please feel free to close this and tell me if there's a better way to contact you.)

**Comment by dhanus** [comment]
@julesfowler Good point! This tutorial is (somewhat embarrassingly) still on python 2. 

We actually will have everything all set up on AWS, so that you don't need to have this working on your laptop to make it through the tutorial -- but it's awesome that you're getting this set up on your laptop in advance as well!  

Thank you for pointing this out!
